language: python
python:
   - "2.6"
   - "2.7"
   - "3.2"
   - "3.3"
   - "3.4"
   - "3.5"
# command to install dependencies
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -y strace fuse libfuse-dev user-mode-linux
   - sudo mknod /dev/fuse c 10 229; sudo chmod 666 /dev/fuse

install: "pip install -r test-requirement.txt"
# command to run tests
script: 
   - test/test_travis.sh py.test # run fuse tests on UML 
   - py.test -k "not Fuse"
